### ISSUE TITLE
Roles are returned upon a rejoin even if the member is role-muted

### ISSUE THREAD

**Issue by Octol1ttle** [LabsDevelopment/Boyfriend#117]
### Description

In the code that returns roles when a member rejoins (GuildMemberJoinedResponder), there is no check to skip returning roles if the member is role-muted.

### Reproduction Steps

1. Mute a member
2. Ask that member to rejoin
3. Their roles will be returned and the mute role will be gone

### Expected behavior

Only the mute role will be returned

### Actual behavior

All roles will be returned

**Comment by mctaylors** [comment]
> ### Expected behavior
> 
> Only the mute role will be returned

Don't forget about `RemoveRolesOnMute` setting.
